---
language: cpp
compiler:
  - gcc
env:
  matrix:
  - BUILD_TARGET=test
  - BUILD_TARGET=release
  - BUILD_TARGET=sample_qt
install:
- ./scripts/travis_ci_install.sh
before_script:
script:
  - ./scripts/travis_ci_build.sh
after_success:
  - ./scripts/coveralls.sh
