--- 
language: cpp
compiler: 
- gcc
env: 
install:
- sudo apt-get install libboost-dev
- sudo apt-get install libboost-thread-dev
- sudo apt-get install libboost-system-dev
- sudo easy_install cpp-coveralls
before_script:
script: 
- make gcov || exit 1
after_success:
- coveralls --root gcov
