---
language: cpp
compiler:
  - gcc
  - clang
env:
  matrix:
  - BUILD_TARGET=test
  - BUILD_TARGET=release
  - BUILD_TARGET=sample_qt
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  -
    if [ "$CXX" = "clang++" ];
    then
        sudo apt-get install -qq libstdc++-4.8-dev;
    fi

  -
    if [ "$CXX" = "g++" ];
    then
        sudo apt-get install -qq g++-4.8;
        export CXX="g++-4.8";
        export CC="gcc-4.8";
    fi
install:
  - sudo apt-get install libboost-dev
  - sudo apt-get install libboost-thread-dev
  - sudo apt-get install libboost-system-dev
  - sudo easy_install cpp-coveralls
  -
    if [ "$BUILD_TARGET" = "sample_qt" ];
    then
        sudo apt-get install qt4-qmake;
        sudo apt-get install libqt4-dev libqt4-gui;
    fi
before_script:
script:
  - $CXX sample/main.cpp -std=c++11 -pthread -o test && ./test
after_success:
  - ./scripts/coveralls.sh
