--- 
language: cpp
compiler: 
  - gcc
env:
  matrix:
  - BUILD_TARGET=test
  - BUILD_TARGET=release
install:
  - sudo apt-get install libboost-dev
  - sudo apt-get install libboost-thread-dev
  - sudo apt-get install libboost-system-dev
  - sudo easy_install cpp-coveralls
before_script:
script: 
  - ./scripts/travis_ci_build.sh
after_success:
  - ./scripts/coveralls.sh
