--- 
language: cpp
compiler: 
- gcc
env: 
install:
- sudo apt-get install libboost-dev
- sudo apt-get install libboost-thread-dev
- sudo apt-get install libboost-system-dev
before_script:
- git submodule init
- git submodule update
script: 
- make && ./subsumption_tests -ojunit
